const el = {
  statusBanner: document.querySelector("#status-banner"),
  statsGrid: document.querySelector("#stats-grid"),
  resetAll: document.querySelector("#reset-all"),
  filtersPanelBody: document.querySelector("#filters-panel-body"),
  modeTabs: [...document.querySelectorAll(".mode-tab")],
  searchInput: document.querySelector("#search-input"),
  sectorFilter: document.querySelector("#sector-filter"),
  areaFilter: document.querySelector("#area-filter"),
  subareaFilter: document.querySelector("#subarea-filter"),
  typeFilter: document.querySelector("#type-filter"),
  sortFilter: document.querySelector("#sort-filter"),
  activeModeLabel: document.querySelector("#active-mode-label"),
  resultCount: document.querySelector("#result-count"),
  selectionLabel: document.querySelector("#selection-label"),
  recordList: document.querySelector("#record-list"),
  detailTitle: document.querySelector("#detail-title"),
  detailSubtitle: document.querySelector("#detail-subtitle"),
  detailBreadcrumbs: document.querySelector("#detail-breadcrumbs"),
  subareaRouteStrip: document.querySelector("#subarea-route-strip"),
  detailFacts: document.querySelector("#detail-facts"),
  detailDescription: document.querySelector("#detail-description")
};
