const el = {
  statusBanner: document.querySelector("#status-banner"),
  statsGrid: document.querySelector("#stats-grid"),
  resetAll: document.querySelector("#reset-all"),
  filtersPanelBody: document.querySelector("#filters-panel-body"),
  modeTabs: [...document.querySelectorAll(".mode-tab")],
  searchInput: document.querySelector("#search-input"),
  sectorFilter: document.querySelector("#sector-filter"),
  areaFilter: document.querySelector("#area-filter"),
  subareaFilter: document.querySelector("#subarea-filter"),
  typeFilter: document.querySelector("#type-filter"),
  sortFilter: document.querySelector("#sort-filter"),
  resultsTitle: document.querySelector("#results-title"),
  resultsMeta: document.querySelector("#results-meta"),
  recordList: document.querySelector("#record-list"),
  detailTitle: document.querySelector("#detail-title"),
  detailSubtitle: document.querySelector("#detail-subtitle"),
  detailDescription: document.querySelector("#detail-description"),
  detailFacts: document.querySelector("#detail-facts")
};
